-- Criacao do banco de dados
CREATE DATABASE SUPERMERCADO;

USE SUPERMERCADO;

-- Criacao da tabela produto
CREATE TABLE PRODUTO(
	IDPRODUTO INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	CATEGORIA VARCHAR(30),
	PRECO FLOAT(10,2),
	DESCRICAO VARCHAR(30),
	FORNECEDOR VARCHAR(30),
	QUANTIDADE INT,
	DATA_CHEGADA DATE
);

-- Criacao da tabela cliente
CREATE TABLE CLIENTE(
	IDCLIENTE INT PRIMARY KEY AUTO_INCREMENT,
	NOME VARCHAR(30),
	ENDERECO VARCHAR(30),
	TELEFONE INT,
	EMAIL VARCHAR(30) UNIQUE,
	DATA_CADASTRO DATE
);

-- Criacao da tabela venda
CREATE TABLE VENDA(
	IDVENDA INT PRIMARY KEY AUTO_INCREMENT,
	DATA_VENDA DATE,
	ID_CLIENTE INT,
	VALOR_TOTAL FLOAT(10,2),
	PAGAMENTO ENUM('DINHEIRO', 'PIX', 'CREDITO', 'DEBITO')
);

-- Criacao da chave estrangeira fk_cliente
ALTER TABLE VENDA ADD CONSTRAINT FK_CLIENTE
FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(IDCLIENTE);

-- Criacao da tabela item_venda
CREATE TABLE ITEM_VENDA(
	IDITEM INT PRIMARY KEY AUTO_INCREMENT,
	ID_VENDA INT,
	ID_PRODUTO INT,
	QUANTIDADE_VENDIDA INT,
	PRECO FLOAT (10,2)
);

-- Criacao das chaves estrageiras fk_id_venda e fk_id_produto
ALTER TABLE ITEM_VENDA ADD CONSTRAINT FK_ID_VENDA
FOREIGN KEY(ID_VENDA) REFERENCES VENDA(IDVENDA);

ALTER TABLE ITEM_VENDA ADD CONSTRAINT FK_ID_PRODUTO
FOREIGN KEY(ID_PRODUTO) REFERENCES PRODUTO(IDPRODUTO);

-- Criacao da tabela estoque
CREATE TABLE ESTOQUE(
	ID_ITEM_ESTOQUE INT PRIMARY KEY AUTO_INCREMENT,
	ID_PRODUTO_ESTOQUE INT,
	QUANTIDADE INT
);

-- Criacao da chave estrangeira fk_id_produto_estoque
ALTER TABLE ESTOQUE ADD CONSTRAINT FK_ID_PRODUTO_ESTOQUE
FOREIGN KEY(ID_PRODUTO_ESTOQUE) REFERENCES PRODUTO(IDPRODUTO);